apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tylerhera/yolo-client:1.0
          ports:
            - containerPort: 3000
          env:
            - name: SERVER_HOST
              value: "server-service"
            - name: SERVER_PORT
              value: "5000"
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
