name: Provision using Ansible and Vagrant
hosts: all
become: true

vars:
    app_name: "{{ app_name }}"
    frontend_port: "80"
    backend_port: "3000"
  tasks:
    - name: Install Docker
      become: yes
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      become: yes
      apt:
        name: docker-compose
        state: present

    - name: Clone Repository
      become: yes
      git:
        repo: https://github.com/tyler-hera/yolo.git
        dest: "/opt/{{ app_name }}"

    - name: Build & Run the Frontend Container
      become: yes
      docker_container:
        name: frontend
        image: tyler-hera/yolo-frontend:latest
        state: started
        ports:
          - "{{ frontend_port }}:80"
        volumes:
          - "/opt/{{ app_name }}/frontend:/app"

    - name: Build & Run the Backend Container
      become: yes
      docker_container:
        name: backend
        image: tyler-hera/yolo-backend:latest
        state: started
        ports:
          - "{{ backend_port }}:3000"
        volumes:
          - "/opt/{{ app_name }}/backend:/app"