---
- name: Configuration Management IP4
  hosts: all
  become: true

  vars:
    app_root_dir: "/vagrant/app"
    frontend_port: "80"
    backend_port: "3000"
    
  tasks:
    - name: Clone Yolo repository
      git:
        repo: https://github.com/tyler-hera/yolo.git
        dest: "{{ app_root_dir }}"
        version: master

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
        validate_certs: no

    - name: Build and run Docker container
      become: true
      docker_container:
        name: frontend
        image: tylerhera/yolo-client:1.0
        state: started
        ports:
          - "{{ frontend_port }}:80"

    - name: Build and run backend container
      become: yes
      docker_container:
        name: backend
        image: tylerhera/yolo-backend:1.0
        state: started
        ports:
          - "{{ backend_port }}:3000"
      
    - name: Open application in browser
      uri:
        url: "http://localhost:3000"
        status_code: 200
      register: app_response

    - name: Display application response
      debug:
        var: app_response.content
